# This file is machine-generated - editing it directly is not advised

[[BIOSSFemCore]]
deps = ["Calculus", "LinearAlgebra", "Logging", "SparseArrays", "StaticArrays"]
git-tree-sha1 = "4a2e80471cf2d7c83e76b10f03cc30df0a4d822f"
repo-rev = "master"
repo-url = "/Users/miguel/Desktop/bioss/lib/biossfemcore/"
uuid = "e6815f29-35bd-4f98-854b-53e447428e18"
version = "0.1.4"

[[BIOSSFemDriver]]
deps = ["BIOSSFemCore", "BIOSSFemElements", "BIOSSFemMaterial", "LinearAlgebra", "SparseArrays", "StaticArrays", "WriteVTK"]
git-tree-sha1 = "9cd477a920e7e64451f475ec7c74b96941caeb74"
repo-rev = "master"
repo-url = "/Users/miguel/Desktop/bioss/lib/biossfemdriver/"
uuid = "f4fbbc3a-31dd-4ed3-b1d4-fdb2c6bc02bc"
version = "0.1.5"

[[BIOSSFemElements]]
deps = ["BIOSSFemCore", "BIOSSFemMaterial", "Calculus", "LinearAlgebra", "SparseArrays", "StaticArrays"]
git-tree-sha1 = "5a2aba22e42502cb462c6a3b47a84e64ddccee89"
repo-rev = "master"
repo-url = "/Users/miguel/Desktop/bioss/lib/biossfemelements/"
uuid = "192dd290-38b7-43f7-a7f3-954434947dc7"
version = "0.1.4"

[[BIOSSFemMaterial]]
deps = ["BIOSSFemCore", "SparseArrays", "StaticArrays"]
git-tree-sha1 = "9e9c8626f36eb5a2c8c18ec4c5072f21d3f970ff"
repo-rev = "master"
repo-url = "/Users/miguel/Desktop/bioss/lib/biossfemmaterial/"
uuid = "70280c4c-b49c-45e8-9586-41dd80c1f3b7"
version = "0.1.4"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinaryProvider]]
deps = ["Libdl", "SHA"]
git-tree-sha1 = "5b08ed6036d9d3f0ee6369410b830f8873d4024c"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.5.8"

[[Calculus]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "f641eb0a4f00c343bbc32346e1217b86f3ce9dad"
uuid = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
version = "0.5.1"

[[CodecZlib]]
deps = ["TranscodingStreams", "Zlib_jll"]
git-tree-sha1 = "ded953804d019afa9a3f98981d99b33e3db7b6da"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.7.0"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[LibGit2]]
deps = ["Printf"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LightXML]]
deps = ["BinaryProvider", "Libdl"]
git-tree-sha1 = "be855e3c975b89746b09952407c156b5e4a33a1d"
uuid = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
version = "0.8.1"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Pkg]]
deps = ["Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[StaticArrays]]
deps = ["LinearAlgebra", "Random", "Statistics"]
git-tree-sha1 = "5a3bcb6233adabde68ebc97be66e95dcb787424c"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.12.1"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TranscodingStreams]]
deps = ["Random", "Test"]
git-tree-sha1 = "7c53c35547de1c5b9d46a4797cf6d8253807108c"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.9.5"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[WriteVTK]]
deps = ["Base64", "CodecZlib", "LightXML", "Random", "TranscodingStreams"]
git-tree-sha1 = "2e762ea03dff8a5d1a5e5aeea2287bc56a4f1b04"
uuid = "64499a7a-5c06-52f2-abe2-ccb03c286192"
version = "1.4.1"

[[Zlib_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "fdd89e5ab270ea0f2a0174bd9093e557d06d4bfa"
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.2.11+16"
